### ISSUE TITLE
Niveau when trying to buy upgrades

### ISSUE THREAD

**Issue by aka-lucifer** [ESX-Org/esx_lscustom#13]
When I try to purchase any vehicle upgrade, such as armor 1, 2, 3, it all says Niveau, however I am using en locale.

**Comment by ElPumpo** [comment]
Yep it's hardcoded. Search for it in the code and replace it, it's not hard to do.

**Comment by ElPumpo** [comment]
Fixed in 84762eb0cf7f08a9bcdc928970dbac20153014c7
