### ISSUE TITLE
Turbo Doesn't work

### ISSUE THREAD

**Issue by ThatZiv** [ESX-Org/esx_lscustom#16]
Well, the turbo doesn't even work...

**Comment by renaiku** [comment]
I don't see your pull request to fix the bug, did you forget to upload it with the comment ?

**Comment by ThatZiv** [comment]
Its ok, I switched to another lscustoms script that's fully in English and more polished ui

**Comment by Lollypop** [comment]
I wrote a fix for this issue in pull request #17
