### ISSUE TITLE
Question: How to get Add-On Liveries working

### ISSUE THREAD

**Issue by HumanTree92** [ESX-Org/esx_lscustom#23]
I have a few Add-on Vehicles that have 2-3 Custom Liveries. But when i go to the LS Customs & go to Stickers it only shows Default. But if i install Mello-Trainer and open it up it under modifications it shows Liveries & the 2-3 Liveries are in there. Also i know they work b/c when i do /car nameofcar sometimes it will popup with the skin. I then /dv the car & respawn it & it will have a different Livery. So then why isn't LS Customs Picking up the Liveries?

**Comment by DJMORL** [comment]
I'm also having the same problem

**Comment by MarioRogue** [comment]
How to add all the vehicles custom customizations as well? (addons)

**Comment by supergeek23** [comment]
where is the solution ?

**Comment by supergeek23** [comment]
I put all of the mod in the stream folder.... But nothing work and the basic custom doesn't work to like window, engine... I can just custom the color of the car...

**Comment by MoravianLion** [comment]
You have to have liveries created as any other YTF file, a tuning part (which includes custom livery for chassis), which 98% addon cars don't have. You can do it yourself in Zmodeler though. Yes, it's a bit time consuming, but the only way how to get liveries into the LSC.

**Comment by ElPumpo** [comment]
Update to https://github.com/ESX-Org/es_extended/commit/5e35663c95135c5980abe9f2daa8de2d95eeac36 and report back thanks.

**Comment by JaroSound** [comment]
Problem still there after update.

**Comment by DefaultLuca** [comment]
here some cheese for everyone,

there is no cycle for the livery,


> Add this to esx_lscustom/client/main.lua (around line 325)

				elseif v.modType == 17 then -- TURBO
					local _label = ''
					if currentMods[k] then
						_label = 'Turbo - <span style="color:cornflowerblue;">'.. _U('installed') ..'</span>'
					else
						_label = 'Turbo - <span style="color:green;">$' .. math.floor(vehiclePrice * v.price[1] / 100) .. ' </span>'
					end
					table.insert(elements, {label = _label, modType = k, modNum = true})


          --LIVERY FIX by DefaultLuca
				elseif v.modType == 48 then -- Livery
					local _label = ''
					local modCount = GetVehicleLiveryCount(vehicle)
					for j = 1, modCount, 1 do
						if j == currentMods[k] then
							_label = _U('stickers') .. ' ' .. j .. ' - <span style="color:cornflowerblue;">'.. _U('installed') ..'</span>'
							--print(_label)
						else
							price = math.floor(vehiclePrice * v.price / 100)
							_label = _U('stickers') .. ' ' .. j .. ' - <span style="color:green;">$' .. price .. ' </span>'
						end
						table.insert(elements, {label = _label, modType = k, modNum = j})
					end

          --END LIVERY FIX by DefaultLuca

				else
					local modCount = GetNumVehicleMods(vehicle, v.modType) -- BODYPARTS

**Comment by SMVampire** [comment]
@DefaultLuca I'm actually having issues with `GetVehicleLiveryCount` always returning -1 even for vanilla cars I know have liveries.

Using `GetNumVehicleMods(vehicle, 48)` and the other assorted commands is actually more reliable for me. I'm not sure if you are seeing the same. Here is my code.

```
				elseif v.modType == 48 then -- Livery
					local _label = ''
					local modCount = GetNumVehicleMods(vehicle, v.modType)
					for j = 1, modCount, 1 do
						local modName = GetModTextLabel(vehicle, v.modType, j)
						if modName ~= nil then
							if j == currentMods[k] then
								_label = GetLabelText(modName) .. ' ' .. j .. ' - <span style="color:cornflowerblue;">'.. _U('installed') ..'</span>'
							else
								price = math.floor(vehiclePrice * v.price / 100)
								_label = GetLabelText(modName) .. ' ' .. j .. ' - <span style="color:green;">$' .. price .. ' </span>'
							end
							table.insert(elements, {label = _label, modType = k, modNum = j})
						end
					end
```

**Comment by DefaultLuca** [comment]
@SMVampire You are right, I couldn't see vanilla liveries.
But, if use `GetNumVehicleMods` I can't see addon/replace liveries.

So, in my case i fixed with:

> 					-- local modCount = GetVehicleLiveryCount(vehicle) works only for addon/replace
>					-- local modCount = GetNumVehicleMods(vehicle, 48) works only for vanilla
>					local modCount = tonumber(GetNumVehicleMods(vehicle, 48) or 0) + tonumber(GetVehicleLiveryCount(vehicle) or 0)


to tested I used a replacement for 'police3' with liveries,
several addon with liveries,
for the vanilla I used the vehicle 'retinue' which has vanilla liveries.
and every vehicle with no livery return empty list as usual, no errors.



Do you see everything fine with your solution?
addon and vanilla?

**Comment by SMVampire** [comment]
@DefaultLuca I didn't test any addon vehicles, and now that I have I am seeing the same. Thanks.

**Comment by ladows** [comment]
how still work livery? i add the code on the ls custom, but not work i still livrey 1,2,3 but i select and not change anything
