### ISSUE TITLE
Vehicle and menu stuck

### ISSUE THREAD

**Issue by Percroy** [ESX-Org/esx_lscustom#27]
Hello,

when a player open a other menu like the phone or a personal menu, the menu for the customization disapear and we are stuck.

I tried to add this :
`DisableControlAction(0, 74, true) -- Telephone H
DisableControlAction(0, 303, true) -- Menu Personnel U
DisableControlAction(0, 167, true) -- Menu Admin F6
DisableControlAction(0, 289, true) -- Menu Job F2
DisableControlAction(0, 168, true) -- Menu Animalerie F7
DisableControlAction(0, 311, true) -- Touche K
DisableControlAction(0, 182, true) -- Touche L
DisableControlAction(0, 244, true) -- Touche M
DisableControlAction(0, 199, true) -- Touche P
DisableControlAction(0, 75, true) -- Touche F

DisableControlAction(0, 24, true) -- Input Attack
DisableControlAction(0, 140, true) -- Melee Attack Alternate
DisableControlAction(0, 141, true) -- Melee Attack Alternate
DisableControlAction(0, 142, true) -- Melee Attack Alternate
DisableControlAction(0, 257, true) -- Input Attack 2
DisableControlAction(0, 263, true) -- Input Melee Attack
DisableControlAction(0, 264, true) -- Input Melee Attack 2

DisableControlAction(0, 12, true) -- Weapon Wheel Up Down
DisableControlAction(0, 14, true) -- Weapon Wheel Next
DisableControlAction(0, 15, true) -- Weapon Wheel Prev
DisableControlAction(0, 16, true) -- Select Next Weapon
DisableControlAction(0, 17, true) -- Select Prev Weapon
DisableControlAction(0, 69, true) -- INPUT_VEH_ATTACK
DisableControlAction(0, 92, true) -- INPUT_VEH_PASSENGER_ATTACK
DisableControlAction(0, 114, true) -- INPUT_VEH_FLY_ATTACK`

But i don't know where. maybe someone could help ?

**Comment by ElPumpo** [comment]
You've modified the script: why would you ever ask for support and open it as an issue here on github??!!
