### ISSUE TITLE
LSC not working after FiveM update (14/10/2018)

### ISSUE THREAD

**Issue by avxstudio** [ESX-Org/esx_lscustom#47]
Hello,there was a FiveM update,but since I have updatedmy FiveM the script doesnt work properly.The LSCs are shown on the map,but if I enter them theres no message saying that I have to press a certain button to open the menu!(There are no errors shown in the console!)

**Comment by eprimex** [comment]
yes there is 
![image](https://user-images.githubusercontent.com/4604233/47117351-ca789080-d26c-11e8-83ee-de724307a184.png)
