### ISSUE TITLE
"You don't have enough money"

### ISSUE THREAD

**Issue by elxaister** [ESX-Org/esx_lscustom#50]
Hello, this is the error that i got "You dont have enough money" when i try to buy any upgrade or cosmetic... 
 i have esx_society starting before esx_lscustom...

Can someone help me please?

**Comment by ElPumpo** [comment]
then idk what you broke

**Comment by augisbud** [comment]
the issue isn't fixed why the fuck do you close the issue?

**Comment by ScaredDonut** [comment]
I found a fix, shame that @ElPumpo didn't dig a little further into this before closing this issue.

Make sure that your mechanic job in the bank has enough money.

Its located in the addon_account_data in your SQL database. Look for society_mechanic and change it to like 100000000.

Cheers mate.

**Comment by HumanTree92** [comment]
> 
> 
> the issue isn't fixed why the fuck do you close the issue?

Quite funny how you assumed it was broke but it wasn't. You where just dumb.

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/esx_lscustom/blob/9a17f31c3ff452f36f507a59d8cf7281910152d0/server/main.lua#L12 bruh

**Comment by Fuzzelz** [comment]
> I found a fix, shame that @ElPumpo didn't dig a little further into this before closing this issue.
> 
> Make sure that your mechanic job in the bank has enough money.
> 
> Its located in the addon_account_data in your SQL database. Look for society_mechanic and change it to like 100000000.
> 
> Cheers mate.

This worked for me thanks brother !!
