### ISSUE TITLE
Sticker / Livery Default?

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_lscustom#56]
While in the Stickers/Livery section, the option says "default", however I can click up and down arrow and then the stickers change. Is there a way to fix this, so instead of "Default" there will be numbers?

**Comment by ElPumpo** [comment]
Have you updated to https://github.com/ESX-Org/es_extended/commit/5e35663c95135c5980abe9f2daa8de2d95eeac36

**Comment by ElPumpo** [comment]
Duplicate of #23
