### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by renaiku** [ESX-Org/esx_lscustom#60]
Hello guys,

Just to say that the license on the readme is under Gizz name when it should be mine.
Could you just change the name with a link to point to my github please ?

Thanks.

**Comment by renaiku** [comment]
Also: 
- https://github.com/ESX-Org/esx_accessories
- https://github.com/ESX-Org/esx_joblisting
- https://github.com/ESX-Org/esx_jobs

**Comment by renaiku** [comment]
- https://github.com/ESX-Org/esx_atm

**Comment by ElPumpo** [comment]
You developed this resource for the ESX organisation, the org has rights to the repo and not you. You betrayed us with shady things, you can frankly fuck off.
