### ISSUE TITLE
BENNY'S update mechanic only

### ISSUE THREAD

**Issue by donnayy** [ESX-Org/esx_lscustom#61]
Hi, the last release don't have the option to mecano job only.
LScustom is free for all players.
Is there anyway to solve it ?
Thank you...

**Comment by ElPumpo** [comment]
It's in the config?

**Comment by donnayy** [comment]
This is the config looks like for  esx_lscustom 2.0.0
Doesn't have the option to mechanic job only

Config              = {}
Config.DrawDistance = 100.0
Config.Locale = 'fr'

Config.Zones = {
    ls1 = {
        Pos   = { x = -337.3863, y = -136.9247, z = 38.5737},
        Size  = {x = 3.0, y = 3.0, z = 0.2},
        Color = {r = 204, g = 204, b = 0},
        Marker= 1,
        Name  = "Los Santos Customs",
        Hint  = _U('press_custom')

**Comment by ElPumpo** [comment]
Then update?!
